### ISSUE TITLE
Set IP address for HK packets

### ISSUE THREAD

**Issue by liuweiseu** [panoseti/panoseti#111]
The IP addresses for HK, IM and PH packets are set, when we run `start.py`.

For IM and PH packets, I think that's fine.

For HK packets, is it better to set the IP address automatically after reboot?  put this step in `config.py --reboot?`
so we can get HK packets immediately after reboot.

**Comment by davidpanderson** [comment]
Done in 0443750f2cca1036d998e6a54f347c15eb21257d
