### ISSUE TITLE
rsync doesn't work, if there are no data files

### ISSUE THREAD

**Issue by liuweiseu** [panoseti/panoseti#112]
If something incorrect happened, hashpipe may not generate data files.

If we run `stop.py` at this time, we will see the error message like this:
`Exception: rsync -P panoseti@192.168.1.102:/mnt/data10/module_1/obs_Lick.start_2022-09-29T00:24:41Z.runtype_eng.pffd/*`

**Comment by davidpanderson** [comment]
I changed things so that if an rsync error occurs,
it prints an error message, continues,
and doesn't write a run_complete file
