### ISSUE TITLE
use same shapers for all modes?  - PH only, image only, dual mode;   or instead we could use different configuations and calibration coefficient for each mode

### ISSUE THREAD

**Issue by danseti** [panoseti/panoseti#118]
we need to decide which shapers we want to use for the different modes,
and how that affects calibration coefficients we use.  and then implement what we decide. 
 
if we want, we could use the same shaper for pulse height only mode, and the pulse height measurements in dual mode.  and the same shaper in image only mode,  and imaging in dual mode.   but they would have to be two different shapers (one shaper for pulse height and a different shaper for imaging). 
 this would allow us to only need one set of calibrations, so the calibrations would
be easier, and the configuration software would be a bit easier. 

jerome pointed out that our current technique is that when we are doing either pulse height or image mode alone,  (not both image and pulse height simulateously, called "dual mode") that we use the same maroc shaper type for both single mode pulse height or single mode imaging.    
we can't use the same shaper in dual mode, so currently, dual mode uses
different set of shapers than the single modes. 

the shaper restrictions are: 

when in dual mode  (pulse height and imaging simultaneously): 
a) if we use unipolar or bipolar shaper for pulse height, then we need to use the half bipolar shaper for image.
b) if we use half bipolar for pulse height, then we need to use either unipolar or bipolar for image. 

for single modes (either image or pulse height single mode) we can use any of the three shapers. 

some emails about this are below: 

----------------------------------

hi jerome, 

i just had a nerdy conversation with rick about what the maroc can and can not do:

when in dual mode  (pulse height and imaging simultaneously): 
a) if we use unipolar or bipolar shaper for pulse height, then we need to use the half bipolar shaper for image.
b) if we use half bipolar for pulse height, then we need to use either unipolar or bipolar for image. 

for single modes (either image or pulse height single mode) we can use any of the three shapers. 

my suggestion:
whatever shapers we are using for dual mode now (a or b above),  
then for single modes we use the same shapers we use in dual mode.  
rationale:  this seems simpler -  as we don't need different calibrations. 

but if you prefer to keep using different shapers for single and dual modes, 
that's fine too - it's not hard to change the software so that it looks at the mode,
and applies a different coefficient, as you suggested yesterday. 
but then your calibration might be harder, as you'd have to produce two different calibrations ?  

best wishes,

dan

On Tue, Oct 25, 2022 at 10:28 AM Maire, Jerome <[jmaire@ucsd.edu](mailto:jmaire@ucsd.edu)> wrote:
Hi Dan,

my understanding is that we are using the half-bipolar shaper in dual-ph mode and the bipolar shaper in other modes (including dual-imaging mode).
I thought we have to use a different shaper in dual mode for imaging and ph modes, we can not use the same shaper. If that's true and if we suse the bipolar shaper for dual-ph mode rather than the half-bipolar, then we will need to use half-bipolar for dual-imaging mode? it seems that in this case we would still have to do some adjustment for dual-imaging mode using the half-bipolar shaper, right?

Thanks,

Jerome
De : Dan Werthimer <[danw@ssl.berkeley.edu](mailto:danw@ssl.berkeley.edu)>
Envoyé : mardi 25 octobre 2022 09:19
À : Maire, Jerome <[jmaire@ucsd.edu](mailto:jmaire@ucsd.edu)>
Cc : Rick Raffanti <[rikraf@techneinstruments.com](mailto:rikraf@techneinstruments.com)>; Wei Liu <[liuwei_berkeley@berkeley.edu](mailto:liuwei_berkeley@berkeley.edu)>; David P. ANDERSON <[davea@berkeley.edu](mailto:davea@berkeley.edu)>; Nicolas Rault-Wang <[nraultwang@berkeley.edu](mailto:nraultwang@berkeley.edu)>; Shelley Wright <[s2wright@ucsd.edu](mailto:s2wright@ucsd.edu)>; Paul Horowitz <[phorowit@g.harvard.edu](mailto:phorowit@g.harvard.edu)>
Objet : unipolar shaper for all modes ?
 

hi jerome, 

yesterday you pointed out that we were using the maroc's bipolar shaper when we are taking pulse height data without image data (single mode), 
and the maroc only allows the unipolar shaper for pulse height when we are in dual mode (taking both pulse height and image data simultaneously).  

and you pointed out the calibration coefficient for the two different shapers is different. 

there are a couple of ways to handle this problem: 

1)  the software could look at the configuration file and figure out whether the user has selected pulse height only mode or  dual mode, 
     and then it could apply a different coefficient (i think you said the coefficient changes from 0.5 to 0.65 ?).

2)  we could always use the unipolar shaper for pulse height measurements, whether in dual mode or not, and always use the same coefficient.   

what do you think ? 

best wishes,

dan

**Comment by liuweiseu** [comment]
Now, we are using Bipolar Fast shaper only for IM mode, Half Bipolar Fast shaper only for PH mode.
The quabo_config.txt is here:
https://github.com/panoseti/panoseti/blob/wei_branch/control/quabo_config.txt
