### ISSUE TITLE
monitor disk space

### ISSUE THREAD

**Issue by davidpanderson** [panoseti/panoseti#121]
goals:
1) Show the user the data rate per module for their config,
and how much recording time there is on each disk.
config.py --disk_space
Based on this, they can change the daq config if needed.

2) Don't let a recording run start unless there is sufficient disk space on DAQ nodes and head node.
A recording run must specify its duration.

3) Stop recording data when duration exceeded.

**Comment by liuweiseu** [comment]
This is implemented in this commit: 00f513c1edfeb195cc5ae329e6cb76b2c1e4a6a8.
