### ISSUE TITLE
warn user if they select 8 bit image mode and long integration time, or implement autoselect of 8 vs 16 bit imaging

### ISSUE THREAD

**Issue by danseti** [panoseti/panoseti#122]
the 8 bit imaging counters can overflow if the integration time is > ~25 us. 
so the code should warn the user if they have selected 8 bit imaging with integration times > 25 us. 

another possibility is that the code could automatically set whether the quabos use 8 bit counters or 16 bit counters for imaging, depending on where the user sets the integration time.

**Comment by davidpanderson** [comment]
We currently have

        if image_8bit:
            if image_usec < 20:
                raise Exception('integration time must be >= 20 usec in 8 bit mode')
        else:
            if image_usec < 40:
                raise Exception('integration time must be >= 40 usec in 16 bit mode')

**Comment by danseti** [comment]
hi dave,

the existing code you discuss below deals whether the four quabo 1 Gbit
ethernet can handle the data rates produced by the quabos
(which depend on the integration time and 8/16 bit) ,
but that code doesn't include limitations about whether the 8 bit counters
might overflow during an integration.

here are suggested configurations for different imaging mode integration
times:

< 20 us :   wont work if there are four quabos in a module, as the data
rate is too high
20-25 us:  8 bit imaging only  (the data rate is too high for 16 bits, and
8 bit counters won't overflow if integration time is < 25 us)
25-40 us:  won't work (the 8 bit counters  might overflow, and with 16 bit
counters the data rate is too high if there are four quobos in a module).
>= 40 us:   only 16 bit imaging mode will work  (8 bit counters might
overflow)


dan






Dan Werthimer
Astronomy Dept and Space Sciences Lab
University of California, Berkeley

**Comment by davidpanderson** [comment]
Fixed in e860ea23965c264424c108d48bc5f537ecca1ee0
