### ISSUE TITLE
sessions and timed runs

### ISSUE THREAD

**Issue by davidpanderson** [panoseti/panoseti#123]
1) add a notion of "session"

    session_start.py
        open dome(s), power on, get quabo UIDs, config Marocs, set HV etc.

    session_end .py
        power off, close domes

2) add a notion of "timed run"
  start.py --nsecs N [--end_session]
    if --dur specified, stop run after N seconds
   if --end_session specified, do session_end.py after that

This would let you start an N-hour run, then go to sleep

**Comment by jeromaire** [comment]
the initialization of the instrument for observations is already implemented in the Observer User interface  ('Initialize instrument' & 'ShutDown Instrument'). Plus, there are a few observing procedures that can not be automated right now (deadman timer, checking dome shutters closed properly, etc...) that will prevent to run a script at the beginning of the night and go to sleep
