### ISSUE TITLE
view snapshots of image and pulse height data during observations 

### ISSUE THREAD

**Issue by danseti** [panoseti/panoseti#125]
shelley and jerome requested that during data acquisition, the observer should be able to see snapshops of the data so they can make sure the instrument is working well during the observation.

e.g.  perhaps every second or so, a program could display images from each of the modules, and display an occasional pulse height event as well (perhaps every few seconds?). 

when we are taking high cadence image data, the images we'd want to display should be sums of ~100 images, to improve SNR.  

i'm not sure how best to implement this:
roughly every second, we'd need to extract about 100 images from the data, either get the data from the output file, or from inside hashpipe, and sum the images and display the sum.

**Comment by davidpanderson** [comment]
Is it OK if the images are displayed as ASCII?

**Comment by jeromaire** [comment]
Hi Dan, I think this is issue is solved. yesterday I tested Panotv using 100us exposure frames from all modules and it was working properly, data flowing correctly and no need to stack to see bright stars (could add stacking as an option). Sorry if I wasn't clear yesterday, this wasn't a request but just thoughts on what to do if  Panotv wouldn't work at that exposure but it was never tested that way. so not sure this feature request is still needed.
