### ISSUE TITLE
quabos crash if pulse height threshold set too low

### ISSUE THREAD

**Issue by danseti** [panoseti/panoseti#128]
the quabos crash if the pulse height threshold is accidently set too low. 

typically the pulse height threshold is set around 12 pe, and the resulting pulse height event rate is a few events per second, easily handled by the quabos.    

if the user accidently sets the threshold to ~2 pe, the pulse height event rate is very high, 
perhaps 1 million events per second, and the quobos can't handle these high event rates.
the result is that  we can't ping any of the four quabos, and all four quabos require a reboot via a power cycle.  

wei, david, and i found if you configure the system for only one quabo in a module (quabo 0), 
that quabo 0 won't hang at a high pulse height event rate, so perhaps that's a clue
that the problem is where we are moving high rate ethernet packets from quabo N+1 to quabo N.  but we only did a very quick test.  and perhaps quabo 0 will hang at a higher rate than we tested, all by itself.    

what might be causing this problem ? : 
perhaps the quabo isn't handling ethernet fifo overflows correctly ? 
or perhaps the firmware that decides whether the microblaze can have access to the ethernet port or whether the pulse height packet generator can have ethernet port access needs to be revised, so that we can still comminicate with the microblaze even though the pulse height packet generator wants to continuously use the ethernet port (e.g. we could implement a round robbin method, or a priority encoder that always gives priority to the microblaze to use the ethernet port ?) . 

dan

**Comment by liuweiseu** [comment]
This bug is fixed in the latest firmware(V20.6&7).
