### ISSUE TITLE
check each quabo to see if it's running the correct version firmware

### ISSUE THREAD

**Issue by danseti** [panoseti/panoseti#129]
jerome and wei noticed on december 16 that two of the quabos at lick, #13 and #15, 
might be running the wrong firmware - they are running BGA firmware, perhaps on QFP boards. 
if so, the pixels from these two boards will be scrambled. 

we should develop code that checks the firmware on each quabo and make it's the correct version for
the two different versions of quabos (those with BGA packaged maroc chips, and older boards with QFP chips). 

i think the production software is already logging which versions are running on all the quabos, 
but i don't think the software is checking to make sure the versions are correct, and if they aren't correct,
it should alert the user, and put a message in the log file.

**Comment by liuweiseu** [comment]
We used pin V13 to check the quabo version.
We thought that if V13 is  pulled up, it's a qfp quabo; if V13 is connected to ground, it's a bga quabo.

However, we found that some of the qfp quabo also connects V13 to ground. (Check 17.08.DN002.v05_QuaboSchematic.pdf and 17.08.DN002.v06_QuaboSchematic.pdf)

Therefore, we can't use pin V13 for the quabo version detection.
