### ISSUE TITLE
change hashpipe code for anytrig function

### ISSUE THREAD

**Issue by liuweiseu** [panoseti/panoseti#131]
In the  latest firmware, one quabo can be trigger other three quabos.
We need to change hashpipe code for this new function.

**Comment by nraultwang** [comment]
a possible plan for these changes:
[https://docs.google.com/document/d/18vHY26J6E1obTqHyXraw_J8AKzOY2CUPsF0LkGp5LNk/edit?usp=sharing](url)

**Comment by liuweiseu** [comment]
Nico has made this change, but we found a bug, which is mentioned in #136.
Let's move there for the next stage.
