### ISSUE TITLE
Redirect quabo output

### ISSUE THREAD

**Issue by davidpanderson** [panoseti/panoseti#14]
Add a quabo command that tells it what IP address to send
1) its HK data
2) image and PH data

Maybe have the ability to send HK to two different addresses
(head node and data recorder)

Currently everything is sent to 192.168.1.100 (hardwired)

Maybe don't send HK data until told to (that way no hardwired IP addrs in quabo).

If a quabo receives a command with the "echo" but set, reply to the IP addr of sender.

**Comment by liuweiseu** [comment]
Now, we added two new commands for Redirect quabo output.
(1) The first command is used for setting IP addresses of IM and PH packets.
     After the command is sent to quabo, a reply with MAC addresses will be sent back from quabo.
     The default IP address of IM and PH packets is 192.168.1.100.
(2) The second command is used for setting IP address of HK packets.
      The default IP address of HK packets is 192.168.1.100.
More information about the two new commands is here:
https://github.com/panoseti/panoseti/blob/master/doc/Panoseti_Quadrant_Board_Interface_rev5.pdf

**Comment by liuweiseu** [comment]
Now, we added two new commands for Redirect quabo output.

(1) The first command is used for setting IP addresses of IM and PH packets.
After the command is sent to quabo, a reply with MAC addresses will be sent back from quabo.
The default IP address of IM and PH packets is 192.168.1.100.

(2) The second command is used for setting IP address of HK packets.
The default IP address of HK packets is 192.168.1.100.

More information about the two new commands is here:
https://github.com/panoseti/panoseti/blob/master/doc/Panoseti_Quadrant_Board_Interface_rev5.pdf
