### ISSUE TITLE
Decide how to structure 32x32 images

### ISSUE THREAD

**Issue by davidpanderson** [panoseti/panoseti#2]
In talking with Ryan, it seems that when we write a 32x32 image to a data file,
it's actually 4 16x16 images written one after the other,
and these images have different orientations,
corresponding to the orientations of the quabos in the module.

Doing things this way may add complexity to data analysis,
e.g. figuring out which pixels are adjacent or where each one is on the sky.

Alternatively, we could shuffle data in the data recorder so that the 32x32 image
is stored in its natural order.
This would use some CPU time in the data recorder but it might be negligible; I could check this.

**Comment by fantonio2** [comment]
Absolutely.  Would be a horrible burden on users of this data if pixels were scrambled.  
CPU time to reorder will be negligible.

**Comment by davidpanderson** [comment]
I measured it at 0.2 microseconds per 32x32 image, which is indeed negligible.

**Comment by ikashell** [comment]
i like the idea of a single 32x32 FITS frame per telescope. We should make sure the re-orientation of the individual quabos is retained in the header/meta-data. This will be needed later for astrometry and distortion solutions.
