### ISSUE TITLE
Pulser on MOBO will not turn off

### ISSUE THREAD

**Issue by ikashell** [panoseti/panoseti#20]
Latest firmware release has it where the LED flasher is always ON and not configurable. We had to cover the LED with black tape at Veritas.

**Comment by danseti** [comment]
does the control software still allow you to switch from the mobo's fiber
flasher to mobo direct LED flasher ?
can you change the rate or brightness of the flasher?  (the only thing you
can't do is turn it off ?)

were you sending commands to the correct quabo (only one quabo can control
the flasher).

thanks,

dan

**Comment by liuweiseu** [comment]
It seems it's the quabo issue(that quabo doesn't work well).

We did a lot of tests in the Berkeley lab, and we can turn on/off the LED on MOBO.
