### ISSUE TITLE
flasher on/off control problem

### ISSUE THREAD

**Issue by danseti** [panoseti/panoseti#25]
flasher can't be turned off or turned on.
not sure if this is only on new mobo ? 
only with new quabo code ?  (it used to work). 
note, wei changed the quabo code to support the new mobo, which has two different flasher LED's (used to be one), 
so now we need to select which flasher is used (on board flasher that shines directly from mobo, or fiber flasher).
perhaps that select bit is wrong, or is affecting other bits (the on/off bit ?).

**Comment by liuweiseu** [comment]
I did some tests on the two Mobos from UCSD.
The flasher works well in the Berkeley lab.

The quabo I used for the test is a new quabo(BGA version) with latest firmware (V0201).
The software I used is the python script: https://github.com/panoseti/panoseti/blob/master/util/control_quabo.py
The cmds I used for the test are: "M"-->"M"-->"A", and then I used "LF0" and "LF1" to select the new or old flasher on the mobo.
