### ISSUE TITLE
Update Storage of Timing data

### ISSUE THREAD

**Issue by ryannova** [panoseti/panoseti#29]
Timing data needs to be saved as a 64 bit integer rather than a string. This needs to be updated in the data acquisition code and the metadata scripts.

**Comment by davidpanderson** [comment]
It's still saved as a string.  The string is a number rather than yyyy:mm:dd:h:m:s

**Comment by ryannova** [comment]
The changes have been made in the metadata scripts and are writing the data as a int rather than string. The data acquisition code doesn't save the full time stamp and only saves the seconds and microseconds, which meets are requirements.
