### ISSUE TITLE
automatically read quabo type, (BGA or QFP package), and load the correct quabo FPGA code 

### ISSUE THREAD

**Issue by danseti** [panoseti/panoseti#36]
when booting the quabo, query at the housekeeping data to see what type of board it is: 
BGA or QFP maroc package board type
then automatically load the appropriate code for that type of quabo board

**Comment by liuweiseu** [comment]
We can't get the board version from the hardware.
The only way to do it for now is checking "board_version" in the quabo_info.json:
https://github.com/panoseti/panoseti/blob/master/quabos/quabo_info.json

The quabo_info.json is generated from Jerome's Panoconfig.mat, and the code for generating this json file is here:
https://github.com/panoseti/panoseti/blob/master/matlab/quabo_info.m
