### ISSUE TITLE
power.py doesn't work at UCSD

### ISSUE THREAD

**Issue by liuweiseu** [panoseti/panoseti#49]
They use a different Ethernet controlled power strip at UCSD, which is from MSN switch(https://www.msnswitch.com/).
The power strips at Lick and UCB are from digital loggers(https://www.digital-loggers.com/).

**Comment by davidpanderson** [comment]
I took a quick look at the MSN site and couldn't find anything about controlling them remotely.
I suggest we standardize on digital loggers.
