### ISSUE TITLE
Set IP addresses for HK, IM and PH packets

### ISSUE THREAD

**Issue by liuweiseu** [panoseti/panoseti#50]
Now, the IP address of HK, IM and PH packets is 192.168.1.100, so the IP address of the head node has to be 192.168.1.100.

Can we set the IP addresses in the control scripts?
This function is supported in the latest firmware(V20.0 and V20.1).

**Comment by davidpanderson** [comment]
The daq_config.json file lets you specify the address of the head node:
https://github.com/panoseti/panoseti/wiki/Configuration-files#daq-config-daq_configjson
