### ISSUE TITLE
turn off module power if it's getting too hot 

### ISSUE THREAD

**Issue by danseti** [panoseti/panoseti#58]
we should implement software that's looking at the quabo temperatures every minute or so, and if the temperatures are getting so high that damage could occur,  the program should turn off power to the module.    
note that several modules can be on one module power supply (up to 20 modules per power supply). 
the program should look at quabo 0 detector temperature of each of the modules operating off that supply, 
and if any of the temperatures exceed the max temperature, all modules running off that supply should be turned by,  by using the ethernet controlled outlet strip to turn off that module power supply

**Comment by davidpanderson** [comment]
implemented in module_temp_monitor.py: b969852fdc21a8b700fc0ba8d14c7731e1775f1c
