### ISSUE TITLE
1024 pixel pulse height image

### ISSUE THREAD

**Issue by danseti** [panoseti/panoseti#72]
currently, when there is a pulse height event, we only record the pulse heights of the 256 pixels on the quabo that had a pixel that triggered the event.  (we record 256 pixels).  

because many cherenkov and other events are found on the edge of this 16x16 pulse height image, 
it would be useful to record all 1024 pixels from all four quabos.  this is especially important for the cherenkov scientists using panoseti instrument to study high energy gamma ray events.  

on quabo we'd need to change the gateware so that when there is a trigger on that quabo, it sends a trigger to the other quabos.   then each quabo would output a 256 pixel pulse height packet along with a time tag, like it does now. 

rick emailed:   
There's a signal, ANYTRIG, on pin 22 of the Mobo connectors, that was reserved for the purpose of triggering all quabos on any trigger, but I don't think we ever implemented it.  

dan, continued: 
later, in post processing, we could identify the four quabo packets that have the roughtly the same time stamp, 
and combine those images into a 1024 pixel pulse height image.

**Comment by liuweiseu** [comment]
The anytrig mode and 2/3 pixel trigger mode have been implemented in the latest firmware(V20.6&7).
