### ISSUE TITLE
pulse height mode trigger on Npixels > threshold  

### ISSUE THREAD

**Issue by danseti** [panoseti/panoseti#77]
this is a request from cherenkov scientist jamie. 

currently the if any of the 256 quabo pixels are above the pulse height threshold, 
all 256 pixels are read out.

jamie and the cherenkov people would like to be able to set the quabo so that it triggers a pulse height readout if
a) one or more pixels are above threshold (the current system)
b) two or more pixels are above threshold
c) three or more 
d) four or more

do implement b,c,d, we wouldn't be able to use imaging mode at the same time as pulse height mode, 
as the 256 pulse height comparators are wire-ored in the maroc chip - 
there's only one output signal to the fpga per 64 pixel maroc, 
so there's no way to tell how many pixels in a maroc are above threshold. 

but the image mode counters have all 256 signals going to the fpga. 
so the fpga could have logic that checks how many pixels are above the image mode threshold. 
we typically set the image mode threshold to 2 or 3 pe, so the counter trigger often. 
in this mode, we'd set the image mode threshold to about 12pe, since we'd be using it as a 

rick compiled a test design that tests if 2 or 3 pixels are above threshold, and found it easily fits in the fpga. 

here's an email chain about this:

rick to dan: 
No, wouldn't meet timing I'd bet.  I think you'd want to register it and pipeline it.

On Wed, Nov 10, 2021 at 6:08 PM Dan Werthimer <[danw@ssl.berkeley.edu](mailto:danw@ssl.berkeley.edu)> wrote:

wow, that far fewer CLBs than i would have guessed. 
i would have guessed the gizmo would need ~255 adders to make an adder tree to add 256 1bit numbers
(Nadders = 128 + 64 + 32 + 64 + 32 + 16+ 8 + 4 + 2 + 1).

how many levels of logic are there in your design? 
are there pipeline registers between the levels? 
will it meet timing?   what is the latency ?  

dan

On Wed, Nov 10, 2021 at 5:54 PM Rick Raffanti <[rikraf@techneinstruments.com](mailto:rikraf@techneinstruments.com)> wrote:
I was wondering what would happen if you just synthesized this:
    reg [7:0] fullsum;
    always @* begin
        for (ii = 0; ii < 256; ii = ii + 1) fullsum = fullsum + data_in[ii];
    end
    assign GOE2 = (fullsum > 2);
    assign GOE3 = (fullsum > 3);

It turns into this schematic:
image.png
Which has this resource utilization:
image.png
Not necessarily the best or right way to do it, just kind of amazing that the tools figure all this out for you

**Comment by liuweiseu** [comment]
We have implemented the 2/3 pixel trigger in the latest firmware(V20.6&7).
