### ISSUE TITLE
GPS Receiver Time and NTP System Time Offset by 0.3 Seconds at Lick Observatory

### ISSUE THREAD

**Issue by ryannova** [panoseti/panoseti#8]
In the current system at Lick Observatory, the time received from the GPS receiver over serial RS232 and the system time (synchronized with stratum 2 (66.220.9.122)) are offset by about 0.3 of a second.

**Comment by liuweiseu** [comment]
I think you mean the time received from WR and the system time are offset by about 0.3 of a second.

The reason may be that WR switch was working on Boundary Clock mode by default, which was not synchronized to the GPS receiver.
We need to configure the WR switch to GrandMaster mode.
