### ISSUE TITLE
change variable name in hashpipe and control script

### ISSUE THREAD

**Issue by liuweiseu** [panoseti/panoseti#86]
The time from WR is TAI time, instead of UTC time (More information about TAI is [here](http://leapsecond.com/java/gpsclock.htm)),
so we may need to change the related variable names, such as chaning 'pkt_utc' to 'pkt_tai'.

**Comment by davidpanderson** [comment]
done in e0bdfa920532b4faacf4015f112734a32219ae46 and 6286a50b2478569d64f21d7834f3d66d90c32665
