### ISSUE TITLE
Currently Ignoring Malformed Packets From GPS Receiver

### ISSUE THREAD

**Issue by ryannova** [panoseti/panoseti#9]
Currently in the script that is used to gather data from the GPS receiver and populating Redis, there are occasional malformed packets were a certain value is usually replaced with bytes '\x10\x10' This is currently ignored simply by looking at the size of the RS232 Packet.

**Comment by liuweiseu** [comment]
The issue is fixed.

The reason is "0x10" is <DLE> byte.
Every <DLE> byte in the data string is preceded by an extra <DLE> byte('stuffing').
